


opts=optimoptions(@ga, ...
    'PopulationSize',100, ...
    'MaxGenerations', 4, ...
    'EliteCount', 2, ...
    'FunctionTolerance', 0, ...
    'PlotFcn', @gaplotbestf);


lb=[0, 0]
ub=[5,5]

[xbest,fbest,exitflag]=ga(@test,2,[],[],[],[],lb,ub,[],opts)